### ISSUE TITLE
UIControl / WindowsKeyPressFcn errors in MATLAB.

### ISSUE THREAD

**Issue by KaptainKris92** [UEFepilepsyAIVI/DeepSqueak#2]
Hi, I have been using the original DeepSqueak for a few weeks and recently have come across this modified version. It seems perfect and I have managed to try it out once, but have since been having problems. 

The software crashes as soon as it loads the detection file and MATLAB command window spits out the errors below. The original DeepSqueak still works fine. I have tried both 2018a and 2020b, both produce this problem. Restarting my computer has helped a few times in the past, but not always. 

Do you have any ideas what the issue could be? Or how I could work around this problem? 

-------------

Error using matlab.ui.control.UIControl/get
Invalid or deleted object.
Error in CreateFocusSpectrogram (line 31)
padding_value_index = get(handles.focusWindowSizePopup,'Value');
Error in update_focus_display (line 4)
[I_f,windowsize_f,noverlap_f,nfft_f,rate_f,box_f,s_f,fr_f,ti_f,audio_f,AudioRange_f,
window_start] =
CreateFocusSpectrogram(handles.data.calls(handles.data.currentcall,:),handles);
Error in update_fig (line 12)
    update_focus_display(hObject,handles);
Error in DeepSqueak>NextCall_Callback (line 260)
    update_fig(hObject, eventdata, handles);
Error in DeepSqueak>figure1_WindowKeyPressFcn (line 395)
        NextCall_Callback(hObject, eventdata, handles)
Error in gui_mainfcn (line 95)
        feval(varargin{:});
Error in DeepSqueak (line 34)
    gui_mainfcn(gui_State, varargin{:});
Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)DeepSqueak('figure1_WindowKeyPressFcn',hObject,eventdata,guidata(hObject)) 
Error using update_fig (line 4)
Error while evaluating DestroyedObject WindowKeyPressFcn.

Error using matlab.ui.control.UIControl/get
Invalid or deleted object.
Error in CreateFocusSpectrogram (line 31)
padding_value_index = get(handles.focusWindowSizePopup,'Value');
Error in update_focus_display (line 4)
[I_f,windowsize_f,noverlap_f,nfft_f,rate_f,box_f,s_f,fr_f,ti_f,audio_f,AudioRange_f,
window_start] =
CreateFocusSpectrogram(handles.data.calls(handles.data.currentcall,:),handles);
Error in update_fig (line 12)
    update_focus_display(hObject,handles);
Error in epoch_window_Callback (line 29)
    update_fig(parent, eventdata, handles) 
Error while evaluating DestroyedObject ButtonDownFcn.

**Comment by leonardolv** [comment]
Hi,
Let us check the issue and we will answer as soon as possible.

Regards,

Leonardo

**Comment by KaptainKris92** [comment]
Hi, 
I believe I've found a solution and it is an issue on my side. Typing 'fclose all' in the command window before launching seems to fix the problem most of the time.
